<?php $_menu = $block->getHtml('', '', 0) ?>

<?php
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$sidebar_megamenu = $ys_helper->getSystemValue('myshop_settings/general/sidebar_megamenu');
?>
<?php if ($sidebar_megamenu): ?>
    <h3 class="title sidemenu_title"><?php echo __('Categories') ?></h3>
    <div class="tonyMenu">
        <nav class="tonyMenu__navbar">
            <ul class="tonyMenu__nav-list">
                <li class="tonyMenu__bth-close dl-close"><a href="#"><span class="icon icon-close"></span><?php echo __('close') ?></a></li>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ms_megamenu_left')->toHtml();?>
                <?php  echo $_menu;  ?>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ms_megamenu_right')->toHtml();?>
            </ul>
        </nav>
    </div>
<?php endif; ?>

