<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php
$_helper = $this->helper('Etheme\Yourstore\Helper\Data');
?>

<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <h4 class="megamenu__subtitle"><span><?php echo __('Currency') ?></span></h4>
    <ul>
        <?php foreach ($currencies as $_code => $_name): ?>
            <li class="currency__item<?php if ($_code == $currentCurrencyCode): ?> active<?php endif; ?>">
                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?> - <?php /* @escapeNotVerified */ echo $_name ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>