<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <div class="currency dropdown" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
        <a class="dropdown-toggle" data-toggle="dropdown">
            <span class="dropdown-label hidden-sm hidden-xs"><?php /* @escapeNotVerified */ echo __('Currency') ?>:</span>
            <?php echo $block->escapeHtml($currentCurrencyCode) ?><span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?> - <?php /* @escapeNotVerified */ echo $_name ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
            <li class="dropdown-menu__close"><a href="#"><span class="icon icon-close"></span><?php /* @escapeNotVerified */ echo __('close') ?></a></li>
        </ul>
    </div>
<?php endif; ?>