<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td>
        <div class="product-image">
            <?php if ($block->hasProductUrl()):?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
               title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()):?>
            </a>
            <?php else: ?>
            </span>
            <?php endif; ?>
        </div>
    </td>
    <td>
        <h5 class="product-title">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
            <?php else: ?>
                <?php echo $block->escapeHtml($block->getProductName()) ?>
            <?php endif; ?>
        </h5>
        <ul class="list-parameters">
            <li>
                <?php if ($_options = $block->getOptionList()):?>
                    <div class="options_s_list">
                    <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <span><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></span>
                            <?php else: ?>
                                <span><?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?></span>
                            <?php endif; ?>
                    <?php endforeach; ?>
                    </div>
                <?php endif;?>
            </li>
            <li class="visible-xs visible-sm">
                <div class="product-price unit-price">
                    <?php if ($canApplyMsrp): ?>
                        <span class="pricing msrp">
                            <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                            <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                                <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                            </a>
                        </span>
                    <?php else: ?>
                        <?php echo $block->getUnitPriceHtml($_item); ?>
                    <?php endif; ?>
                </div>
            </li>
            <li class="visible-xs visible-sm">
                <div class="detach-quantity-mobile">

                </div>
            </li>
            <li class="visible-xs visible-sm">
                <div class="product-price subtotal">
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart msrp subtotal">--</span>
                    <?php else: ?>
                        <?php echo $block->getRowTotalHtml($_item); ?>
                    <?php endif; ?>
                </div>
            </li>
        </ul>
        <?php if ($messages = $block->getMessages()): ?>
            <?php foreach ($messages as $message): ?>
                <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    </td>
    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <div class="product-price unit-price">
                <?php echo $block->getUnitPriceHtml($_item); ?>
            </div>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="detach-quantity-desctope">
            <div class="input">
                <label><?php /* @escapeNotVerified */ echo __('Qty') ?>:</label>
                <div class="style-2 input-counter control qty">
                    <span class="minus-btn"></span>
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="text"
                           size="5"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                    <span class="plus-btn"></span>
                </div>
            </div>
        </div>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
        <div class="product-price subtotal">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php echo $block->getRowTotalHtml($_item); ?>
            <?php endif; ?>
        </div>
    </td>
    <td>
        <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
    </td>
</tr>
</tbody>
