<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_helper = $this->helper('Etheme\Yourstore\Helper\Data');
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <h4 class="megamenu__subtitle"><span><?php echo __('Language') ?></span></h4>
    <ul>
    <?php foreach ($block->getStores() as $_lang): ?>
        <li class="languages__item<?php if ($_lang->getId() == $block->getCurrentStoreId()): ?> active<?php endif; ?>">
            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                <span class="languages__item__flag flag"><img src="<?php echo $_helper->getBaseUrl().'wysiwyg/yourstore/flags/'.$block->escapeHtml($_lang->getCode()).'.png'; ?>" /></span>
                <span class="languages__item__label"><?php echo $block->escapeHtml($_lang->getName()) ?></span>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>