<div class="pp-buttons-container">
    <button id="<?php echo $block->getId() ?>" type="button" onclick="<?php echo $block->getOnclick() ?>" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only <?php echo $block->getButtonClass(); ?>">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>