<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="block-aside widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <h3 class="title">
        <?php echo __('Recent Posts') ?>
    </h3>
    <div class="categories-list">
        <ul class="list-simple">
        <?php foreach ($_postCollection as $_post) { ?>
            <li>
                <a href="<?php echo $_post->getPostUrl() ?>">
                    <?php echo $block->escapeHtml($_post->getTitle()) ?>
                </a>
            </li>
        <?php } ?>
        </ul>
    </div>
</div>
<?php } ?>