<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Rss
 */
?>
<div class="block-aside widget block block-rss" data-bind="scope: 'blog-rss'">
    <h3 class="title">
        <i class="fa fa-rss" aria-hidden="true"></i>
        <a target="_blank" href="<?php echo $this->getUrl('blog/rss/feed') ?>"><?php echo __('RSS Feed') ?></a>
    </h3>
</div>