<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <!-- breadcrumbs -->
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li>
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                                <span><?php echo $block->escapeHtml($crumbInfo['label']) ?></span>
                            </a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                        <?php else: ?>
                            <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </section>
    <!-- /breadcrumbs -->
<?php endif; ?>