<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post post-holder-<?php echo $_post->getId() ?>">
    <div class="title-block">
        <?php $collection = $_post->getParentCategories(); ?>
        <?php if ($_categoriesCount = $_post->getCategoriesCount()) : ?>
        <div class="post-tag">
            <?php foreach($collection as $ct) { ?>
                <a href="<?php echo $ct->getCategoryUrl(); ?>"><?php echo $ct->getTitle(); ?></a>
            <?php } ?>
        </div>
        <?php endif; ?>
        <div class="post-title">
            <h2><a href="<?php echo $_postUrl ?>"><?php echo $_postName; ?></a></h2>
        </div>
        <div class="post-meta">
            <span class="post__meta__item">
                <?php if($_post->getAuthor()): ?>
                <span class="autor"><?php echo __('by') ?> <b><?php echo $_post->getAuthor()->getTitle(); ?></b></span>
                <?php endif; ?>
                <span class="time"><?php echo __('on') ?> <?php echo $_post->getPublishDate('M'); ?> <b><?php echo $_post->getPublishDate('d'); ?>, <?php echo $_post->getPublishDate('Y'); ?></b></span>
            </span>
        </div>
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
        <div class="post-img">
            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
            </a>
        </div>
        <?php } ?>
    </div>
    <div class="description">
        <?php echo $block->getShorContent() ?>
        <?php echo $block->getShortContent($_post); ?>
    </div>
    <?php $collection2 = $_post->getRelatedTags(); ?>
    <?php if ($_tagsCount = $_post->getTagsCount()) : ?>
    <div class="post-meta separators">
        <span class="item">
            <?php echo __('Tag:') ?>
            <?php foreach($collection2 as $ct2) { ?>
                <a href="<?php echo $ct2->getTagUrl(); ?>"><?php echo $ct2->getTitle(); ?></a>
            <?php } ?>
        </span>
    </div>
    <?php endif; ?>
    <div class="optional-block">
        <div class="post-link-more">
            <a href="<?php echo $_postUrl ?>" class="btn btn-underline"><?php echo __('Read More') ?></a>
        </div>
        <div class="post-social-icon">
            <div class="addthis_toolbox addthis_default_style"
                 addthis:url="<?php echo $_postUrl ?>"
                 addthis:title="<?php echo $_postName; ?>"
                <?php if ($firstImage = $_post->getFirstImage()) { ?>
                    addthis:media="<?php echo $firstImage ?>"
                <?php } ?>>
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
        </div>
    </div>
</div>
