<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */


$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$f_open = $ys_helper->getSystemValue('myshop_settings/product_listing/sidebar_collapse');
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="account-nav collapse-block<?php if($f_open): ?> open<?php endif; ?>">
    <div class="collapse-block_title">
        <strong><?php /* @escapeNotVerified */ echo __('My Account'); ?></strong>
    </div>
    <div class="collapse-block_content">
        <ul class="items">
            <?php echo $block->getChildHtml();?>
        </ul>
    </div>
</div>
