<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <li>
    <a href="#"
       class="action towishlist"
       data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>'
       data-action="add-to-wishlist"><span class="fa fa-heart-o"></span><span class="text"><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span></a>
    </li>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
        }
    }
</script>
