<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions-toolbar">
    <div class="secondary"><a class="action back link-functional" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><i class="icon icon-keyboard_arrow_left"></i><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a></div>
</div>