<?php
/* comment */
use Magento\Framework\App\Action\Action;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$image_helper = $this->helper('Magento\Catalog\Helper\Image');
$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$image_width=265;
$image_height=340;
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$sale_label = $ys_helper->getSystemValue('myshop_settings/product_listing/sale_label');
$new_label = $ys_helper->getSystemValue('myshop_settings/product_listing/new_label');
$specials_counter = $ys_helper->getSystemValue('myshop_settings/product_listing/specials_counter');
$quick_view = $ys_helper->getSystemValue('myshop_settings/product_listing/quick_view');

$class_array = array(3, 4, 13, 14, 23, 24);
?>

<?php if (!$_productCollection->count()): ?>

    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>

<?php else: ?>

    <?php $i=0; ?>
    <?php foreach ($_productCollection as $_product): ?>
    <?php $i++; if ($i > $block->getLimit()) break; ?>
    <div class="element-item <?php echo $block->getHtmlClass()?><?php if(in_array($i, $class_array)) { echo ' double-size'; } ?>">
        <div class="product_holder">
            <div class="product_inside">
                <div class="image-box">
                    <?php if ($new_label): ?>
                        <?php echo $this->helper('Etheme\Myshop\Helper\Data')->newLabel($_product); ?>
                    <?php endif; ?>
                    <?php if ($sale_label): ?>
                        <?php echo $this->helper('Etheme\Myshop\Helper\Data')->saleLabel($_product); ?>
                    <?php endif; ?>
                    <?php
                    if ($quick_view):
                        $buttonStyle = 'weltpixel_quickview_button_' . $ys_helper->getSystemValue('weltpixel_quickview/general/button_style');
                        $productUrl = $this->getUrl('weltpixel_quickview/catalog_product/view', array('id' => $_product->getId()));
                        echo '<a class="weltpixel-quickview quick-view '.$buttonStyle.'" data-quickview-url=' . $productUrl . ' href="javascript:void(0);"><span><span class="icon icon-visibility"></span>' . __("Quick view") . '</span></a>';
                    endif;
                    ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <?php if ($specials_counter): ?>
                        <?php echo $this->helper('Etheme\Myshop\Helper\Data')->getCountdown($_product); ?>
                    <?php endif; ?>
                </div>
                <?php
                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <h2 class="title">
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                </h2>
                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                <div class="description">
                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                </div>
                <div class="product_inside_hover">
                    <div class="product_inside_info">
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

                        <?php if ($_product->isSaleable()): ?>
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form class="form_addtocart" data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button type="submit"
                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                        class="action tocart primary btn-product_addtocart">
                                    <i class="icon icon-shopping_basket"></i><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>

                            </form>
                        <?php else: ?>
                            <?php if ($_product->getIsSalable()): ?>
                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                            <?php else: ?>
                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <a href="#"  class="quick-view btn" data-toggle="modal" data-target="#ModalquickView">
                                    <span>
                                    <span class="icon icon-visibility"></span>QUICK VIEW
                                    </span>
                        </a>
                        <ul class="product_inside_info_link">
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                <li class="text-right">
                                    <a href="#"
                                       class="wishlist-link"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span class="fa fa-heart-o"></span>
                                        <span class="text"><?php echo $block->escapeHtml(__('Add to Wish List')); ?></span>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php
                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                            ?>
                            <li class="text-left">
                                <a href="#"
                                   class="compare-link"
                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                   role="button">
                                    <span class="fa fa-balance-scale"></span>
                                    <span class="text"><?php echo $block->escapeHtml(__('Add to Compare')); ?></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" data-toggle="modal" data-target="#ModalquickView" class="quick-view">
                                    <span class="icon icon-visibility"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; ?>


    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>


<?php endif;?>
