<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
?>
<li>
<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getPostDataParams();?>'
        data-role="add-to-links"
        class="action tocompare"><span class="fa fa-balance-scale"></span><span class="text"><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span></a>
</li>
