<?php
$_theme_helper = $this->helper('Etheme\Myshop\Helper\Data');
?>
<div class="container-fluid">
    <div class="row">
        <div class="img-box right-offset">
            <img src="<?php echo $_theme_helper->getMediaUrlBase()?>custom-block-01-bg.jpg" alt="">
            <div class="box-arrow-top-right">
                <div class="animation-hover">
                    <div class="svg-icon">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
										<path   transform="matrix(-1 0 0 1 300 0)"  d="M234.625,393.808c0,0,86.365,97.951,151.666,151.666s37.917,13.692,37.917,16.852c0,3.16,104.27,73.727,183.263,111.643
											c78.993,37.917,133.761,43.183,168.518,45.289c34.757,2.106,38.97,0,38.97,0s-86.365-4.213-117.963-20.012
											c-31.597-15.799,55.822,15.799,117.963,5.266c62.141-10.532,70.567-22.118,70.567-22.118s-230.659,42.012-409.709-125.394
											s-179.05-175.832-179.05-175.832s52.662,51.609,116.909,50.555c64.247-1.053,85.312-48.449,50.555-58.981
											S217.773,237.929,217.773,237.929s-10.532-12.639-44.236,6.319s-33.704,18.958-33.704,18.958s51.609,78.993,71.62,218.02
											s21.065,182.21,21.065,182.21l15.799-54.768"/>
									</svg>
                    </div>
                    <div class="text">
                        Stay in touch and<br>
                        stay in style
                    </div>
                </div>
            </div>
            <div class="description">
                <div class="block-table">
                    <div class="block-table-cell text-left">
                        <div class="container">
                            <div class="subscribe-box">
                                <div class="title"><?php echo __('Get the latest news delivered daily!') ?></div>
                                <p>
                                    <?php echo __('Give us your email and you will be daily updated with<br>the latest events, in detail!') ?>
                                </p>
                                <form class="form form-inline"
                                      novalidate
                                      action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
                                      method="post"
                                      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                                      id="newsletter-validate-detail">
                                    <label class="sr-only" for="email"><?php echo __('Email') ?></label>
												<span class="addon-icon">
												<span class="icon icon-email"></span>
												</span>
                                    <input name="email" type="email" id="newsletter" placeholder="<?php echo __('Enter your e-mail') ?>" class="form-control addon-icon" data-validate="{required:true, 'validate-email':true}"/>
                                    <button type="submit" title="<?php echo __('Subscribe') ?>" class="action"><span><?php echo __('Subscribe') ?></span></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

