<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$minicart_boxed = $ys_helper->getSystemValue('myshop_settings/header_settings/minicart_boxed');
?>
<div class="cart">
    <div class="dropdown" data-block="minicart">
        <a class="dropdown-toggle action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" data-bind="scope: 'minicart_content'">
            <span class="icon icon-shopping_basket"></span>
            <span class="counter qty empty badge badge-cart" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                <!-- ko if: getCartParam('summary_count') -->
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('summary_count') -->
                <span class="counter-number">0</span>
                <!-- /ko -->
            </span>
            <div class="dropdown-label hidden-sm hidden-xs"><?php /* @escapeNotVerified */ echo __('Your Bag'); ?></div>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart empty dropdown-menu slide-from-top<?php if($minicart_boxed) { echo ' basket-small'; } ?>"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
            "appendTo":"[data-block=minicart]",
            "triggerTarget":".showcart",
            "timeout": "2000",
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":[]}}'>
                <div id="minicart-content-wrapper" class="container" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
        <?php endif ?>
    </div>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>