<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>

<?php
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$f_open = $ys_helper->getSystemValue('myshop_settings/product_listing/layered_filter');
?>

<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<!--<div class="filter-current collapse-block<?php if($f_open): ?> open<?php endif; ?>">-->
<div class="filter-current collapse-block">
    <div class="block-subtitle filter-current-subtitle collapse-block_title_static"
            role="heading"
            aria-level="2"
            data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */ echo __('Shopping by') ?></div>
    <div class="collapse-block_content_static">
    <ol class="items filter-list">
        <?php foreach ($_filters as $_filter): ?>
            <li class="item">
                <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                if ($clearLinkUrl):
                    ?>
                    <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                    </a>
                    <a class="action remove"
                       title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                        <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                    </a>
                <?php else: ?>
                    <a class="action remove link-close icon icon-close" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                        <span><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
    <?php if ($block->getLayer()->getState()->getFilters()): ?>
        <div class="block-actions filter-actions">
            <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear btn btn-underline color-defaulttext2"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
        </div>
    <?php endif; ?>
    </div>
</div>
<?php endif; ?>
