<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$f_open = $ys_helper->getSystemValue('myshop_settings/product_listing/sidebar_collapse');
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if (!$wrapOptions): ?>
                    <div class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <div class="collapse-block filters_row<?php if($f_open): ?> open<?php endif; ?>">
                            <div data-role="heading" aria-level="3" class="collapse-block_title"><?php echo $block->escapeHtml(__($filter->getName())) ?></div>
                            <div class="collapse-block_content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                        </div>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
