<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="login-form-box">
    <h2><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></h2>
    <p>
        <?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?>
    </p>
    <form class="form form-login"
          action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
          method="post"
          id="login-form"
          data-mage-init='{"validation":{}}'>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="icon icon-person_outline"></span>
                </span>
                <input name="login[username]" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="icon icon-lock_outline"></span>
                </span>
                <input name="login[password]" placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-5">
                <button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button>
            </div>
            <div class="col-md-12 col-lg-7">
                <ul class="additional-links">
                    <li><a href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></a></li>
                </ul>
            </div>
        </div>

    </form>
</div>
