<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- footer-copyright -->
<div class="container footer-copyright">
    <div class="row">
        <div class="col-lg-12"><?php echo $block->getCopyright() ?></div>
    </div>
</div>
<a href="#" class="btn btn--ys btn--full visible-xs" id="backToTop">Back to top <span class="icon icon-expand_less"></span></a>
<!-- /footer-copyright -->