<?php
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$loader = $ys_helper->getSystemValue('myshop_settings/general/show_load');
?>
<?php if($loader): ?>
    <div class="loader-wrapper">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="loader-animation" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
            </svg>
        </div>
    </div>
<?php endif ?>