<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="search">
    <a href="#" class="search-open"><span class="icon icon-search"></span></a>
    <div class="search-dropdown">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="input-outer">
                <input id="search"
                       data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                       type="text"
                       name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                       value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                       placeholder="<?php /* @escapeNotVerified */ echo __('Enter keyword'); ?>"
                       class="input-text"
                       maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                       role="combobox"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       autocomplete="off"/>
                <div id="search_autocomplete" class="search-autocomplete"></div>
                <button type="submit" class="btn-search"><span><?php /* @escapeNotVerified */ echo __('Search'); ?></span></button>
            </div>
            <a href="#" class="search-close"><span class="icon icon-close"></span></a>
        </form>
    </div>
</div>

