<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
$ys_helper = $this->helper('Etheme\Myshop\Helper\Data');
$products_size = $ys_helper->getSystemValue('myshop_settings/product_listing/products_size_row');
$sale_label = $ys_helper->getSystemValue('myshop_settings/product_listing/sale_label');
$new_label = $ys_helper->getSystemValue('myshop_settings/product_listing/new_label');
$specials_counter = $ys_helper->getSystemValue('myshop_settings/product_listing/specials_counter');
$quick_view = $ys_helper->getSystemValue('myshop_settings/product_listing/quick_view');

if ($products_size == 0) { $classes_set = ' col-xs-6 col-sm-4 col-md-4 col-lg-one-three'; }
if ($products_size == 1) { $classes_set = ' col-xs-6 col-sm-4 col-md-4 col-lg-one-six'; }
if ($products_size == 2) { $classes_set = ' col-xs-6 col-sm-4 col-md-4 col-lg-one-fourth'; }
if ($products_size == 3) { $classes_set = ' col-xs-6 col-sm-4 col-md-4 col-lg-one-two'; }
?>
<?php if (!$_productCollection->count()): ?>
    <div class="on-duty-box">
        <img src="<?php echo $block->getViewFileUrl('images'); ?>/empty-category-icon.png" alt="">
        <h1 class="block-title large"><?php /* @escapeNotVerified */ echo __('Empty Category') ?></h1>
        <div class="description">
            <?php /* @escapeNotVerified */ echo __('There are no products matching the selection.') ?>
        </div>
    </div>
<?php else: ?>
    <div class="toolbar-top">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $rowType = '';
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $rowType = ' row-view';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="product-listing row products list items product-items<?php echo $rowType; ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product-item'.$classes_set.'">' : '</div><div class="item product-item'.$classes_set.'">' ?>
                <div class="product-item-info product_holder" data-container="product-grid">
                    <div class="product_inside">
                        <div class="image-box">
                            <?php if ($new_label): ?>
                                <?php echo $this->helper('Etheme\Myshop\Helper\Data')->newLabel($_product); ?>
                            <?php endif; ?>
                            <?php if ($sale_label): ?>
                                <?php echo $this->helper('Etheme\Myshop\Helper\Data')->saleLabel($_product); ?>
                            <?php endif; ?>
                            <?php
                                if ($quick_view):
                                    $buttonStyle = 'weltpixel_quickview_button_' . $ys_helper->getSystemValue('weltpixel_quickview/general/button_style');
                                    $productUrl = $this->getUrl('weltpixel_quickview/catalog_product/view', array('id' => $_product->getId()));
                                    echo '<a class="weltpixel-quickview quick-view '.$buttonStyle.'" data-quickview-url=' . $productUrl . ' href="javascript:void(0);"><span><span class="icon icon-visibility"></span>' . __("Quick view") . '</span></a>';
                                endif;
                            ?>
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                            <?php if ($specials_counter): ?>
                                <?php echo $this->helper('Etheme\Myshop\Helper\Data')->getCountdown($_product); ?>
                            <?php endif; ?>
                        </div>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h2 class="title">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                            </h2>

                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <?php if ($showDescription):?>
                                <div class="description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </div>
                            <?php endif; ?>
                            <div class="product_inside_hover">
                                <div class="product_inside_info">
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form class="form_addtocart" data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary btn btn-product_addtocart">
                                                <i class="icon icon-shopping_basket"></i><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>

                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($quick_view):
                                        $buttonStyle = 'weltpixel_quickview_button_' . $ys_helper->getSystemValue('weltpixel_quickview/general/button_style');
                                        $productUrl = $this->getUrl('weltpixel_quickview/catalog_product/view', array('id' => $_product->getId()));
                                        echo '<a class="weltpixel-quickview quick-view btn '.$buttonStyle.'" data-quickview-url=' . $productUrl . ' href="javascript:void(0);"><span><span class="icon icon-visibility"></span>' . __("Quick view") . '</span></a>';
                                    endif;
                                    ?>
                                    <ul class="product_inside_info_link">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <li class="text-right">
                                                <a href="#"
                                                   class="wishlist-link"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span class="fa fa-heart-o"></span>
                                                    <span class="text"><?php echo $block->escapeHtml(__('Add to Wish List')); ?></span>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <li class="text-left">
                                            <a href="#"
                                               class="compare-link"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <span class="fa fa-balance-scale"></span>
                                                <span class="text"><?php echo $block->escapeHtml(__('Add to Compare')); ?></span>
                                            </a>
                                        </li>
                                        <?php if ($quick_view): ?>
                                        <li>
                                            <?php
                                                $buttonStyle = 'weltpixel_quickview_button_' . $ys_helper->getSystemValue('weltpixel_quickview/general/button_style');
                                                $productUrl = $this->getUrl('weltpixel_quickview/catalog_product/view', array('id' => $_product->getId()));
                                                echo '<a class="weltpixel-quickview quick-view '.$buttonStyle.'" data-quickview-url=' . $productUrl . ' href="javascript:void(0);"><span class="icon icon-visibility"></span></a>';
                                            ?>
                                        </li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
